### ISSUE TITLE
Issue with Pillow/PIL ImageCms library

### ISSUE THREAD

**Issue by litmount** [pyston/pyston_v2#160]
When trying to use the ImageCms library from Pillow I get the following error.

`  File "/home/ranpan/.local/lib/pyston3.8/site-packages/PIL/ImageCms.py", line 170, in __init__
    self._set(core.profile_open(profile), profile)
  File "/home/ranpan/.local/lib/pyston3.8/site-packages/PIL/_util.py", line 19, in __getattr__
    raise self.ex
  File "/home/ranpan/.local/lib/pyston3.8/site-packages/PIL/ImageCms.py", line 23, in <module>
    from PIL import _imagingcms
ImportError: cannot import name '_imagingcms' from 'PIL' (/home/ranpan/.local/lib/pyston3.8/site-packages/PIL/__init__.py)`

 I also test this with the latest Pyston version with the same result. Works fine in regular Python3

**Comment by undingen** [comment]
This fixed the issue for me:
```
sudo apt-get install liblcms2-dev
pip install --force-reinstall pillow
```
This is because all binary packages need to be compiled from source for Pyston because no third party packaged wheels are currently available. This means one needs to have the development packages of the dependencies installed.

I found the optional 3rd party packages for Pillow here: https://pillow.readthedocs.io/en/latest/installation.html#external-libraries
If e.g. you also require webp support you will need to make sure libwebp-dev is installed.

Hope this helps.

**Comment by litmount** [comment]
Thanks for the reply @undingen 
I did what you said and still have the same error.
Not sure what I am missing.

**EDIT:**
I needed reinstall pillow with the option --no-cache-dir (I found that in the link you gave)
All is working now! Thanks again for getting me in the right direction. Super Helpful!
