### ISSUE TITLE
Cannot install Tensorflow

### ISSUE THREAD

**Issue by PLPeeters** [pyston/pyston_v2#165]
Hi,

No matter how I go about it, I cannot seem to install Tensorflow. Using pip yields:

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

Using pip with the wheel referenced [here](https://www.tensorflow.org/install/pip) for Python 3.8 on Linux yields:

```
ERROR: tensorflow_cpu-2.7.0-cp38-cp38-manylinux2010_x86_64.whl is not a supported wheel on this platform.
```

I did try this dirty hack:

```
wget https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.7.0-cp38-cp38-manylinux2010_x86_64.whl
mv tensorflow_cpu-2.7.0-cp38-cp38-manylinux2010_x86_64.whl tensorflow_cpu-2.7.0-py3-none-any.whl
pip install tensorflow_cpu-2.7.0-py3-none-any.whl
```

but then it fails later when trying to install `tensorflow-io-gcs-filesystem`:

```
ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem>=0.21.0 (from tensorflow-cpu) (from versions: none)ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem>=0.21.0 (from tensorflow-cpu) (from versions: none)
```

Is this something you can somehow fix on your end?

**Comment by undingen** [comment]
The problem is that Pyston in not binary compatible so every compiled package must be compiled for Pyston. Most packages supply source packages so while pip installing a package it will compile it for you if it can't find a binary one. Unfortunately this is not true for tensorflow (and some other large libraries with lots of dependencies) which don't supply source packages. 
We are working on providing support for building wheels for Pyston and hope that eventually 3rd party packages for Pyston are also provided but for now it's unfortunately that for these packages one has to manually download the source and follow the install instructions supplied by the 3rd party package.
I guess you would run into the same issue if you use the latest development version of CPython for example. 

We do have a compiled tensorflow for Pyston as conda package: https://anaconda.org/pyston/tensorflow/files maybe you can use that instead? More infos are here: https://github.com/pyston/pyston/wiki/Using-conda

UPDATE: posted wrong link

**Comment by PLPeeters** [comment]
So it's Tensorflow not providing a source package that confused me, that explains things.

I'll probably end up manually compiling from the source then. As usual, thanks for the _very_ quick response and insights!
