### ISSUE TITLE
Package WRF-Python could not install via conda but sucessful via pip

### ISSUE THREAD

**Issue by david-tao-as01** [pyston/pyston_v2#197]
With conda, I got this error message:
Encountered problems while solving:
  - package wrf-python-1.3.2-py38h0e9072a_2 requires python_abi 3.8.* *_cp38, but none of the providers can be installed

But with pip, it was successfully installed. I've tested some of my python code using wrf-python under pyston 2.3.3 but haven't encountered any error yet. So, not quite sure what is going on in conda wrf-python installation.

**Comment by kmod** [comment]
I wish we could do something about the cryptic error messages, but this means that there is no prebuilt version of that package for Pyston -- the error message is because conda thinks the best thing to do in that case is try to install the CPython version but it fails.

pip has the ability to compile packages from source, but I believe conda does not. So if we haven't built the package already, you'll have to ping us to build it (or your could build it yourself, but it's somewhat unwieldy). I went ahead and built a version of this package, does it work for you now?

**Comment by david-tao-as01** [comment]
> I wish we could do something about the cryptic error messages, but this means that there is no prebuilt version of that package for Pyston -- the error message is because conda thinks the best thing to do in that case is try to install the CPython version but it fails.
> 
> pip has the ability to compile packages from source, but I believe conda does not. So if we haven't built the package already, you'll have to ping us to build it (or your could build it yourself, but it's somewhat unwieldy). I went ahead and built a version of this package, does it work for you now?

Thanks for your helping! it's totally working now.

**Comment by kmod** [comment]
Great! Glad to hear it.
