### ISSUE TITLE
Which license does pyston-lite use?

### ISSUE THREAD

**Issue by saumzzz** [pyston/pyston_v2#303]
Hey guys so I was trying to understand under which license is `pyston-lite`  distributed?

The `LICENSE` file references the license of python itself and not about `pyston` or `pyston-lite`

**Comment by kmod** [comment]
Yeah we just stuck with the PSF license (aka `LICENSE`) since a lot of the code we're distributing is from CPython and is under that license. I can see how not mentioning pyston could lead to some confusion about whether this was intentional or not, and we can see about adding something to the license to clear that up a bit.

**Comment by saumzzz** [comment]
Hey @kmod thanks for clearing that up!!
