### ISSUE TITLE
The best way to detect Pyston?

### ISSUE THREAD

**Issue by vytas7** [pyston/pyston_v2#36]
Hi!
I was testing whether Pyston could speed up the [Falcon web framework](https://falconframework.org) and other stuff I'm tinkering with, and the results were more than impressive; for some scenarios I was getting up to 2x.

We normally ship Falcon "cythonized" on CPython, compiling even a large portion of our pure Python code base with Cython, which gives a performance boost. However, it seems that this is a de-optimization on Pyston, as I assume Pyston's JIT does something similar, but more efficiently. OTOH, we also have some handcrafted "true" Cython `cdef` code, which is still advantageous even on Pyston.

Ideally, if Pyston gains traction (wishing you the best heh :slightly_smiling_face:), we'd like to detect it, and build only those specialized extensions with Cython.

What is the best way to do that (detect Pyston)?
Right now, it is masquerading almost as CPython 3.8.8, only the `python_compiler` is different:
```python
>>> import platform
>>> platform.python_implementation()
'CPython'
>>> platform.python_version()
'3.8.8'
>>> platform.python_compiler()
'Pyston 2.2.0, GCC 9.3.0'
```
Is `python_compiler` the way to go?

**Comment by undingen** [comment]
Oh wow nice - good to hear that you are seeing so good results running Falcon via pyston :+1: 
Because we don't do any unboxed types and have to support all the python frame introspection, tracing etc stuff I'm not surprised that handcrafted cython is currently faster.

I'm not 100% sure whats the best way to test for it (@kmod will know) but internally we are currently using: `hasattr(sys, "pyston_version_info")`.

**Comment by kmod** [comment]
I'm not 100% sure what the best way is either since this whole area is a bit trial-and-error -- we have to figure out the right amount of masquerading to make things work, and I think our current amount is good but it's not clear.

But yes I think for now checking for `sys.pyston_version_info` is probably the safest and most future-proof.

**Comment by vytas7** [comment]
Thanks @undingen and @kmod !
That does answer my question :+1: 

I've created an issue, maybe we'll choose to provide first class Pyston support and tuning in a future release :wink:
