### ISSUE TITLE
`platform.python_implementation()` returns "CPython"

### ISSUE THREAD

**Issue by rocky** [pyston/pyston_v2#39]
In Pyston 2.2: 

```
$ python
Python 3.8.8 (heads/rel2.2:6287d61, Apr 29 2021, 15:46:12)
[Pyston 2.2.0, GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
rocky's .pythonrc loaded
>>> import sys, platform
>>> platform.python_implementation()
'CPython'
>>> "Pyston" in sys.version
True
```

The code from v1 could be used though: https://github.com/pyston/pyston_v1/blob/6d392ba7a5882139e8a6ad8bf5165abd5f32f2d3/from_cpython/Lib/platform.py#L1465

**Comment by kmod** [comment]
This is a rather delicate issue akin to picking a user-agent string, and I'm not 100% sure we can change this. We've run into code that is something like

```
if implementation == "CPython":
  doNormalThing()
elif implementation == "PyPy":
  doSpecialPyPyThing()
else:
  raise Exception("not supported")
```

though I don't remember where `implementation` in my example came from.

My takeaway is that we should have some tests so that we can know whether we can change something like this, because right now I think it's fairly risky.

**Comment by rocky** [comment]
I wasn't suggesting that the code that I had in the Python interactive session is how would fix this (although it is the workaround I am using - the burden of my code outside is my worry). 

If you look at #40 the way this is handled is not to do any testing at all but return "Pyston" because if the code comes from this code base it is Pyston.

**Comment by kmod** [comment]
What I'm saying is that while it's easy to code up this change (as you did in #40), it will require good testing to know if this is something that we want. The exact semantics of these functions are defined by how they are used by the community, and we've done a little bit of testing to find the best set of compatibility markers to get different projects to work. Unfortunately I don't remember the exact details at this point, but there is code like the pseudocode I listed earlier that could break with your change: your change will signal to certain code that we are not compatible with CPython. I wish there was a `sys.is_compatible_with_cpython` flag but since there's not this might be one of the ways that we have to signal compatibility.

**Comment by mattip** [comment]
> The exact semantics of these functions are defined by how they are used by the community, and we've done a little bit of testing to find the best set of compatibility markers to get different projects to work

I think this is misleading. You should "tell the truth" in the implementation name and go through the process of submitting pull requests to help projects adopt Pyston. The same should be done with `sys.implementation.name`, as well as C-level macros that define pyston version as well. It is true all of this is a lot of work, but it allows projects like NumPy to figure out when the implementation is Pyston.

**Comment by kmod** [comment]
I agree that one should tell the truth, but empirically these flags have become CPython-compatibility flags, not descriptive flags of which implementation is running. There are ways to test for Pyston (we're currently recommending `hasattr(sys, "pyston_version_info")` but I believe that unfortunately the ship has sailed on many of the original flags serving their intended purpose since they were never used that way by the Python community. I do have aspirations to improve the situation as a whole, but I believe that the strategy of branching on the implementation name is fundamentally flawed, and the community should move to a feature-flag model.

Coming at this from another angle, should different versions of CPython have different implementation names? Should the patched versions of CPython that distros provide be a different implementation? At what point are two binaries "different implementations"?

**Comment by mattip** [comment]
> empirically these flags have become CPython-compatibility flags, not descriptive flags of which implementation is running

Can you point to public discussions that support this? Different versions of CPython have `sys.version_info` and the corresponding C macros and these are in wide use to distinguish between versions. If a distro changes behaviour (like removing recursion limits or refcounting) then indeed, that becomes a different implementation. Are you actually claiming that Pyston is **not** a different implementation of Python?

**Comment by kmod** [comment]
I believe your comment supports my point: version info is put in other fields, not in the implementation name. We're a patched version of CPython with a high level of compatibility, and there is no particular bright line to make a binary division of "same" / "different implementation". There are a multitude of features that an implementation can support or not, and there's no rule that a priori makes sense for saying what's "enough". As another example, a normal build of CPython doesn't support all the features that a debug build does, but they also share the same implementation name.

We've gone through and looked at which features are in practice guarded by which compatibility markers, and for the features currently guarded by the implementation name we behave the same as CPython. Other markers guard features where we are not the same, and we indicate appropriately that we are a different implementation.

I agree that another approach would have been to fix the state of compatibility-checking in the Python ecosystem, and it is true that we did not and decided to meet the community where it's currently at.

**Comment by rocky** [comment]
> There are ways to test for Pyston (we're currently recommending `hasattr(sys, "pyston_version_info")`

Ok - if this is what you recommend, this is what I'll start using to check for Pystonality. Is this documented anywhere other than here? The more important facet of this other place, is that if this decision changes it will be mentioned there.

**Comment by mattip** [comment]
> We're a patched version of CPython with a high level of compatibility

Here is where we differ. Please keep an open mind going forward, this approach may limit the ability of libraries to use Pyston. The NumPy issue will be the first of many as you try to get adoption across the enormous Python ecosystem. There was also a Cython issue that requested a C macro to detect the version of Pyston since the C API changed, which met with the same "it is your problem" approach.

**Comment by kmod** [comment]
@rocky good point, I just added a note to the README

@mattip I confess I'm confused, we've picked our approach (signal CPython but give #defines and sys fields for detecting us) based on maximum compatibility and alignment with the rest of the ecosystem, and I thought you were saying we should have gone a more technologically pure route despite the compatibility hit (saying we're not CPython and having to patch other peoples' projects). What are you proposing that we should do?

I'm unfamiliar with the Cython issue you are referencing, the only [Cython compatibility issue](https://github.com/cython/cython/issues/4200) I'm aware of was resolved by using the C version defines that we already add, could you link me to the one you're mentioning?

**Comment by mattip** [comment]
The Cython comment referred to  [this comment](https://github.com/cython/cython/issues/4200#issuecomment-853896888) where the macro support is not rich enough to allow a simple hex version detection but the idea of a more complete macro was dismissed and in the end the choice was made to totally drop older version support.

I am suggesting that you not signal CPython.

**Comment by kmod** [comment]
Apologies if we gave the wrong impression, we were not trying to dismiss the idea of the hex version, we just thought the most expedient option was to use the define that we already added. We're planning on adding the hex version for our next release.

The "older version" that was dropped was Pyston v1, which supported a completely different set of features. Since that project is dead we thought it would reduce confusion to remove the handling of it. For example I remember looking at some Cythonized code and thinking that Cython was producing incorrect Pyston-specific behavior, and it took me a second to realize that the define they were checking for was only set in Pyston v1.

I hear your suggestion. I think we're in agreement that compatibility is an important goal, I just think that empirically there are far far more issues caused by changing the implementation name than are addressed by it. And even if we were able to patch the universe of Python code, limiting Pyston to only being able to run post-2021 code is a non-starter.

**Comment by mattip** [comment]
Ok, thanks. Rereading my comments, I apologize, I overstepped the norms of polite conversation. I was chasing down a stack overflow due to this kind of issue: PyPy + cython caused a crash in scipy, as it turns out, no fault of PyPy. That one [I found]](https://github.com/scipy/scipy/issues/14363), there is still a [numpy + PyPy + windows](https://github.com/conda-forge/numpy-feedstock/pull/238#issuecomment-876128309) problem to be tracked down.

**Comment by callegar** [comment]
To me, returning `CPython` seems a bit _unpythonic_ (“explicit is better than implicit”). Yet, I understand that there is also something that is certainly _pythonic_ about it (“practicality beats purity”).
About the example presented above as a reason to keep `CPython`, namely
```
if implementation == "CPython":
  doNormalThing()
elif implementation == "PyPy":
  doSpecialPyPyThing()
else:
  raise Exception("not supported")
```
I wonder if it really pushing in such a direction sense. Yes, you do not want legacy code to break on `pyston` because of checks like that. On the other hand, you would like checks like that to be definitely corrected _early_ while `pyston` is in an adoption phase, rather than to stay `pyston`-unaware forever. And getting people to write
```
implementation = platform.python_implementation()
if implementation in ("CPython", "Pyston"):
  doNormalThing()
elif implementation == "PyPy":
  doSpecialPyPyThing()
else:
  raise Exception("not supported")
```
would definitely not be bad. Most important in case it comes out that for certain things it is necessary to `doSpecialPystonThing()` that would be easily extendable by the addition of an `elif` branch, while calling users to write
```
implementation = platform.python_implementation()
if implementation == "CPython":
  if ( ...some other test to verify we are Pyston...):
    doPystonThing()
  else:
    doNormalThing()
elif implementation == "PyPy":
  doSpecialPyPyThing()
else:
  raise Exception("not supported")
```
would be particularly ugly.

Why not returning `Pyston` that seems the honest, explicit thing to do and adding a `--pretend` flag to the `pyston` command line or a check for an environment variable (e.g., `PYSTON_PRETEND_CPYTHON`) to make it return `CPython` for the corner cases?

**Comment by kmod** [comment]
I'll answer your question with a question: what is the bright-line test for when `platform.python_implementation()` should return a different value?

Put another way: we are more similar to upstream CPython than CPython minor versions are to each other. Why should we return a different value for this function but CPython minor versions should all report the same thing?


But I think the crux of the debate here is a normative vs descriptive one. I would love if the community had used `python_implementation()` in the way that was originally intended, and as you argue for here. But realistically the actual semantics of that function are defined by the way that the community ended up using them, semantics which I believe strongly support us returning "CPython".

You're advocating for us changing the Python ecosystem to match the way we'd like the world to work, which is a noble goal but not one we have the resources for. If you change the ecosystem for us we would be happy to make this switch :)

**Comment by h-vetinari** [comment]
> Put another way: we are more similar to upstream CPython than CPython minor versions are to each other. Why should we return a different value for this function but CPython minor versions should all report the same thing?

I think this is a red herring. You may be compatible, but it does not make you CPython.

> But realistically the actual semantics of that function are defined by the way that the community ended up using them, semantics which I believe strongly support us returning "CPython".

You are (understandably!) trying to jumpstart your compatibility with the ecosystem by returning `"CPython"`. But - not least due to Hyrum's law - inevitable behavioural differences between implementations will occur, and by faking the implementation, you rob library authors of any decent mechanism to account for that.

Any library that _does_ make use of `python_implementation()` (and I believe it's not that widespread) clearly intends to control low-level details about this, and deserves to explicitly opt into supporting pyston, by adding `elif python_implementation() == "Pyston":` as necessary. Granted, it's a slower path to having widespread Pyston usage, but it's IMO clearly the right (and only long-term sustainable) approach for the ecosystem.

**Comment by kmod** [comment]
We are a fork of CPython; Github contains 20.4k forks of CPython, are these also "not CPython"? Where's the line?

It seems like a point of disagreement is that the people on this thread have not seen how the different version-detection functions are actually used. Perhaps you are inferring semantics based on the name or based on the original documentation, but if you look at the code that uses these functions you will see a different set of semantics. Several people have recommended a certain semantic for this function (which as above I think is ill-motivated), but I find the state of the Python ecosystem to be far more convincing than peoples' hunches about how they would like a function to work.

To be more specific, Python lacks a meaningful "feature flag" system, so people test for all sorts of things in various imperfect ways. The code I was referring to was checking whether the implementation provides a `libpython.so` library to link against, and is clearly not doing anything ABI- on optimization-level-specific which would distinguish CPython from CPython+Pyston. Also for what it's worth we provide several documented ways of checking if Pyston optimizations are enabled.

As much as I understand and empathize that people would like the Pyston developers to take it upon ourselves to improve the state of cross-implementation-compatibility in the Python ecosystem, it's not going to happen. The Pyston team is politely declining to do the work that you are asking us to do, but since it sounds like there are some strongly opinionated people on this thread perhaps there is a critical mass to implement these improvements as a community effort.

**Comment by kmod** [comment]
I can understand peoples' frustration from having the sense that Pyston is making the situation worse, but again I believe the difference of opinion comes down to whether or not people have seen how these things are used in the wild. I believe the evidence is quite strong that based on the current state of the ecosystem we actually are satisfying the most peoples' intentions by returning "CPython" here.

**Comment by h-vetinari** [comment]
> We are a fork of CPython; Github contains 20.4k forks of CPython, are these also "not CPython"? Where's the line?

Those forks are neither branded nor distributed, but I can see that we're not going to agree on this.

I've opened a (hopefully neutrally worded) discussion on [discuss.python.org](https://discuss.python.org/t/opinions-about-alternative-implementations-returning-platform-python-implementation-cpython/11296) in case some CPython developers want to chime in.

**Comment by malemburg** [comment]
Let me add another angle to this discussion :-)

If you want to add a new return value to the set of defined return values of platform.python_implementation(), you should first open an issue on the Python bug tracker asking for this. At this point, the only allowed return values are documented as  ‘CPython’, ‘IronPython’, ‘Jython’, ‘PyPy’ (see https://docs.python.org/3/library/platform.html#platform.python_implementation

On the topic of where to draw the line, please consider that the current set of return values (except for 'CPython') are true reimplementations of the Python spec, not just forks of the reference implementation. If an application needs to have more fine-grained control, the forks should provide other means of identifying the fork's name, e.g. via special attributes in the sys module or other support modules.

**Comment by mikeshardmind** [comment]
I'd prefer the truth over a lie here. Just as you don't have the resources to change the whole ecosystem, a maintainer with little demand for pyston support may not be able to justify testing pyston and ensuring that the differences don't cause unintended issues with their own limited resources. (or even that they are aware of pyston!) You've broken the documented way for people in that position to make an informed decision, and in cases where a problem could come up as a result of this, It's almost always better to fail early and in a predictable way.

The line for me is that you distribute pyston, intend for adoption, and are not 100% compatible. There may be 20k forks of python, but there aren't 20k groups intending distribution for widespread consumption.

>> At this point, the only allowed return values are documented as ‘CPython’, ‘IronPython’, ‘Jython’, ‘PyPy’ 

> Possible return values are: ‘CPython’, ‘IronPython’, ‘Jython’, ‘PyPy’.

This isn't stated as "the only possible return values", the phrasing does not preclude other values here.

**Comment by kmod** [comment]
I think everyone on this thread agrees that "truth" is good, "lies" are bad, and Pyston should return what people "expect". We all agree that there should be a way to determine the details of the implementation that is being used.

The difference of opinion is about the expected semantics of the `platform.python_implementation()` function and whether this is the appropriate place for this distinction to be made. There are several other ways of inspecting the version of Python you are running, and people seem to be up in arms about that this should be another one. I assume that this interpretation is based on the name and the documentation, but it's hard to be sure because people have not defended their view beyond just saying that *a* method should exist (despite the existence of other methods).

I'll restate my position: based on a reading of the actual consumers of this function, package maintainers would expect us to return "cpython". This is because the community semantics of this function are "is the installation structure CPython's or PyPy's", not "what are all the details of the Python implementation we are running".

I hear the commenters on this thread loud and clear, but it appears there is a difference between what GitHub commenters think about this function and what real-world code expects. The Pyston team has to make a choice between these two audiences, and we are choosing the code. I understand that this is disappointing to the people on this thread but I think the issue is different than what most people are making it out to be.

At this point the same issues are being rehashed and I don't think very much value is being generated, so I'd encourage people to use the "reaction" button at this point. If you'd like to advocate for a different semantics for this function I'd encourage you to go to the [upstream location](https://discuss.python.org/c/packaging/14) where these sorts of things are decided, instead of commenting here.
