### ISSUE TITLE
Pyston can't get freetype2 version because ZLIB 1.2.9 is not found

### ISSUE THREAD

**Issue by rocky** [pyston/pyston_v2#41]
I've been trying pyston 2.2 for running an open-source Mathematica called [Mathics](https://mathics.org)

Using it is about 25-30% faster than CPython as advertised. Thanks!

In doing this and running package [wordcloud](https://pypi.org/project/wordcloud/) 

I get this traceback in part...

```
  File "/src/external-vcs/github/mathics/Mathics/mathics/builtin/drawing/image.py", line 2560, in _word_cloud
    wc.generate_from_frequencies(freq)
  File "/home/rocky/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/wordcloud/wordcloud.py", line 496, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)
  File "/home/rocky/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/PIL/ImageFont.py", line 853, in truetype
    return freetype(font)
  File "/home/rocky/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/PIL/ImageFont.py", line 850, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/rocky/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/PIL/ImageFont.py", line 173, in __init__
    freetype_version = parse_version(features.version_module("freetype2"))
  File "/home/rocky/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/home/rocky/.pyenv/versions/pyston-2.2/lib/pyston3.8/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
```

What is going on above is that `version` from the call `parse_version(...("freetype2")` is coming back `None` and that is because the dynamic loader is not finding`ZLIB_1.2.9`:

```
 __import__('PIL._imagingft')
** ImportError: /home/rocky/.pyenv/versions/pyston-2.2/lib/pyston3.8/lib-dynload/../../../lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)
```

**Comment by kmod** [comment]
Thanks for the report! Did you install from the portable build or the debian package?

Also if you could provide a way to reproduce this error that would help us look into it.

**Comment by rocky** [comment]
I used `pyenv install pyston-2.2` which I think is the portable build package: 

```
Python 3.8.8 (heads/rel2.2:6287d61, Apr 29 2021, 15:46:12)
[Pyston 2.2.0, GCC 9.3.0]
```

As for a program:

```
$ cat /tmp/bug.py
from wordcloud import WordCloud
wc = WordCloud()
freq = {'albert': 1, 'einstein': 2}
wc.generate_from_frequencies(freq)
```

```

**Comment by rocky** [comment]
> Thanks for the report! Did you install from the portable build or the debian package?
> 

Hmm...  If 
```
Python 3.8.8 (heads/rel2.2:6287d61, Apr 29 2021, 15:46:12)
[Pyston 2.2.0, GCC 9.3.0]
```

doesn't make it clear which this is, then `Python -V` should make the distinction more clear (if it doesn't already).

**Comment by kmod** [comment]
Ok, I didn't get the exact same error as you, but what I'm seeing is:
- If I do `import PIL._imagingft` in a script it works and then your test script finishes without error
- The `from . import _imagingft` in `site-packages/PIL/ImageFont.py` is failing (unless _imagingft was already imported)

The libz issue looks like a problem with our portable release, but I'm not sure why it would occur based on where the import was happening. Hopefully @undingen could take a look into the libz issue since he knows more about the portable release

**Comment by undingen** [comment]
I think the problem is caused by a mismatch between the included old version of `libz.so.1` in the portable release and the newer system one which `_imagingft` linked against :/.
This error should therefore not happen when using the pyston deb package. (`pyenv install pyston-2.2` is using the portable archive which comes with the old shared objects instead).

Letting it pick up the system libraries over the included ones fixed the problem for me.
E.g. `LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/ python` or renaming/removing the included `libz.so.1`

I'm not really sure how we can fix this probably :/. 
Is there a mechanism to tell linux to only use our included shared objects as a fallback if the system ones don't exist?

**Comment by undingen** [comment]
I recreated the portable release with the #83 fix applied which fixes your problem - you can download it here:
https://github.com/pyston/pyston/releases/download/v2.3/pyston_2.3_portable-v3.tar.gz
