### ISSUE TITLE
Targeting Python 3.9

### ISSUE THREAD

**Issue by stuaxo** [pyston/pyston_v2#68]
Hi,
   Thanks for pyston - I was able to run a test suite about 20% faster.
It would be great if there was a release for 3.9.
PEP-585, made a lot of improvements to pythons type annotations and is part of python 3.9
I had to backport code to work with 3.8 to work with Pyston - it was worth it but it would be nice to not need to.

Best Regards
Stuart

**Comment by kmod** [comment]
We'd love to, though we're still thinking through our strategy for which version(s) to target.

**Comment by stuaxo** [comment]
Is there a plan for major releases every so often, a bit like how pypy seems to be every 6 months ?

**Comment by kmod** [comment]
I suppose it depends on what you mean by "major release". The current plan is to only use minor version bumps (ex from 2.3 to 2.4) for ABI-breaking releases, which we are mostly trying to avoid. If it ends up that we want to do a bunch of ABI changes, then I guess we'd come up with a plan for batching them together in some way. If we're not breaking the ABI then personally I think it makes sense to release whatever we have on a fairly-frequent basis. That said, we haven't done many releases of the core interpreter recently because we've mostly been working on packaging improvements which aren't part of a core release, but we're currently putting together a 2.3.2 release to roll up some bug fixes.

We're planning on doing a large change later in this year to retarget CPython versions, which will necessitate an ABI breakage (since CPython doesn't maintain their ABI between minor versions). Our current thinking is to start migrating to 3.11 during the 3.11 beta, so that we can release a 3.11-targeted Pyston around the same time that CPython 3.11 is officially released. We haven't decided yet exactly what our CPython-targeting strategy will be, since it depends in part on what users end up wanting, but personally my guess is that as long as CPython continues to change things fairly fundamentally for improved performance, we'll keep migrating to their latest releases as they come out.

**Comment by stuaxo** [comment]
Thanks for the info - I'm thinking of seeing if we want to use pyston at work (I have been myself for a few months - but the backporting to 3.8 on our side was a little informal), so this is good information and I'll definitely keep an eye on things.

From my side the 30 percent or so increase in speed for our unit tests has been worthwhile, and I recently found out we have some processes that take a number of house so it may help there too.

**Comment by kmod** [comment]
That's awesome! We'd love to hear how it goes.

**Comment by kmkolasinski** [comment]
Hi, what's the current status of migrating pyston to python 3.11 ?

**Comment by kmod** [comment]
We haven't started; our loose plan is to try to have it ready shortly after 3.11 is released in October.

**Comment by kmkolasinski** [comment]
Hi, thanks that's cool :+1:

**Comment by stuaxo** [comment]
I know things always take longer so, no pressure :) any update on how porting to versions after 3.8 is going ?

**Comment by undingen** [comment]
We are currently porting `pyston_lite` to more Python versions and should soon have a new release which will (likely) be compatible with CPython 3.7 to including 3.10.  At the same time we are upstreaming Pyston changes into CPython in order to make it easier to port it to newer versions.
`pyston_lite` 3.11 support will follow afterwards (I guess around the time 3.11 is released but depends on how many changes it requires). "Full" Pyston rebase to 3.11 is much more work and and I don't know currently when this will happen.

**Comment by stuaxo** [comment]
Great stuff, thanks for the updates, will definitely be following this :)

**Comment by stuaxo** [comment]
I tend to hop around between contracts, so I'm going to close this as I'm no longer working on the project I was hoping to use newer pyston on - I have ticked the option to watch releases though, so I'll still keep an eye on this for personal projects.

**Comment by kmod** [comment]
Sorry I forgot to update this thread -- we [just released](https://blog.pyston.org/2022/09/29/announcing-3-7-3-10-support-and-a-new-direction/) pyston_lite support for 3.7 through 3.10, so please let us know if that works for you!
