### ISSUE TITLE
Repo size - Submodules / Parallel Building Memory Usage

### ISSUE THREAD

**Issue by danieldjewell** [pyston/pyston_v2#75]
Two issues:

1. With all the submodules, the git pack files *alone* are 3.7GiB and with everything checked out it's in the neighborhood of 6 GiB... It would be nice to try and slim that down if possible. (Can git submodules be set to do a shallow fetch?)

2. Building in parallel (```make -j```) on a VM with 32 cores exposed (the physical hardware is 2x Xeon 8-core with hyperthreading, so 16 threads/CPU) results in ~64 parallel jobs running - at least in the llvm/bolt phase. The trouble with this is:
  * Massive memory usage (something like 20GB)
  * Probably slower build times (depending on what I'm building, I find that 24-30 jobs is actually fastest ... because the hyperthreading isn't actually another core.)
  * The normal make options like ```-j16``` aren't respected - when I try this, bolt and llvm appear to build in parallel but using one thread each. 
  * I haven't tested the I/O impact specifically, but using all the cores can definitely run into interesting situations where the build is I/O limited and not processor limited. (I'm not using NVMe drives in this case...)

**Comment by kmod** [comment]
1. It looks like there are some flags that allow you to do shallow submodules
2. You're right, the issue here is that we're using ninja to build llvm, and ninja uses its own parallelism. I think the solution is just to switch our cmake invocation to use the makefile generator instead of ninja.

I'm on vacation and away from my work computer, but I could review a PR if you're interested in tackling these!

**Comment by kmod** [comment]
Ok we implemented the second part, and the first part is now being discussed in #79
